name: 'build and test'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity minimal --logger html -r TestResults --settings coverlet.runsettings
    - name: Publish coverage report to coveralls.io
      uses: codecov/codecov-action@v1
      with:
        file: ./TestResults/**/coverage.info